name: "Pull Request Analytics"

on:
  workflow_dispatch:
    inputs:
      report_date_start:
        description: "Report start date (dd/MM/yyyy)"
      report_date_end:
        description: "Report end date (dd/MM/yyyy)"

jobs:
  create-report:
    name: "Generate PR Report"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2

      - name: "Run Pull Request Analytics"
        uses: AlexSim93/pull-request-analytics-action@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_OWNER_FOR_ISSUE: "marleenlukei"
          GITHUB_REPO_FOR_ISSUE: "DecisionTreeAndRandomForest.jl"
          GITHUB_OWNERS_REPOS: "marleenlukei/DecisionTreeAndRandomForest.jl"
          SHOW_STATS_TYPES: "timeline, workload, pr-quality, code-review-engagement, response-time"
          CORE_HOURS_START: "9:00"
          CORE_HOURS_END: "19:00"
          TIMEZONE: "Europe/Berlin"
          REPORT_DATE_START: ${{ inputs.report_date_start }}
          REPORT_DATE_END: ${{ inputs.report_date_end }}
          EXECUTION_OUTCOME: "new-issue"
